### ISSUE TITLE
Create auth window for web-service (front-end) :(

### ISSUE THREAD

**Issue by Xandr070** [ImmortalIdiot/RUTLead-Web-Frontend#1]

**Comment by rachhhen** [comment]
![Image](https://github.com/ImmortalIdiot/RUTLead-Web-Frontend/assets/147819969/74eb77cc-fa77-4023-bb70-b83964cdaa14)

**Comment by Xandr070** [comment]
Try to make the text input fields thinner

**Comment by rachhhen** [comment]
> Try to make the text input fields thinner

Done

**Comment by Xandr070** [comment]
Good job
